### PR TITLE
Add new publication for mkFit

### PR DESCRIPTION
**Pull request by srlantz**

### CODE REVIEW

**Comment by srlantz** [comment]
I sent the following inquiry to owner@iris-hep.org a week ago and haven't heard back, so I'm seeing if this is a better channel for my question:

Hi, the mkFit project has a couple of publications that are listed on the IRIS-HEP website as preprints submitted to CHEP23. However, the proceedings of CHEP23 have now been published, and all the latest data about the publications (including links to the preprints) are now found at [inspirehep.net](http://inspirehep.net/).

Therefore, it seems to me that the 2 corresponding files should be updated with the inspire-id: field filled in. Should I also rename the files with their inspire-id names, e.g., 12345678.yml? Or just change the fields within the 2 files (osschar-chep23-*.yml), without renaming them?

And I suppose in either case, fields in the files like title:, link:, date:, and citation: should be deleted, so that these fields get picked up from [inspirehep.net](http://inspirehep.net/), correct?

Thanks,
Steve

**Comment by rct225** [comment]
@henryiii Any thoughts?

**Comment by henryiii** [comment]
Yes. I'd go ahead and rename them as well.

**Comment by srlantz** [comment]
> Yes. I'd go ahead and rename them as well.

Pushed a commit taking care of this. Ready to merge.

**Comment by henryiii** [comment]
Were you also going to remove the other fields (not `project:`) and rely on `inspire-id:`?

**Comment by srlantz** [comment]
Oops. Thought I did, but apparently those changes didn't get added to the commit. Will add and push again.

**Comment by henryiii** [comment]
Thanks!

**Pull request merged**
