### PR TITLE
Nov 2020 update for Alexander Held

### PR DESCRIPTION
**Pull request by alexander-held**
This adds two talks (Snowmass workshop + IRIS-HEP blueprint workshop) and the now published CHEP proceedings on likelihood-free inference.

### CODE REVIEW

**Comment by henryiii** [comment]
I think Inspire started adding YYYY-MM dates and that broke something else recently. I can port the fix in here soon to see if that's the problem.

**Comment by alexander-held** [comment]
Thanks @henryiii! I was looking through the log and wondering what could have gone wrong here.

**Comment by henryiii** [comment]
Ouch! I already backported the fix, but the date is YYYY only! Wow. (see https://inspirehep.net/api/literature/1832223 under imprints)

**Comment by henryiii** [comment]
I think in this case it might be better to manually include the date (`date: 2020-01-01`) instead of trying to guess it - you might be able to do better than Jan 1.

**Comment by alexander-held** [comment]
Ok, I will add the date in a few minutes.

**Comment by alexander-held** [comment]
I added the publication date (see https://doi.org/10.1051/epjconf/202024506026), INSPIRE lists a later date (maybe the date it was indexed there?).

**Pull request merged**
