### PR TITLE
initial stab at videos per person/fa/project

### PR DESCRIPTION
**Pull request by davidlange6**
This PR adds videos of talks already on the iris-hep YouTube channel and embeds them on the project and focus area pages. It also creates a /videos.html page for the 12 most recent ones (adding all seems to do bad things to my computer..). 

The yml came from the YouTube+indico apis. It does need a cleanup pass as the video descriptions are not always structured in the same way. I'd like to do that as a followup PR if we are happy with the yml structure. Only one yml file has a non-empty focus-area or project filled in

### CODE REVIEW

**Comment by henryiii** [comment]
Shouldn't speaker be a shortname?

**Comment by henryiii** [comment]
Also, this doesn't tie videos to presentations at all, is that desired?

**Comment by davidlange6** [comment]
short names are valid, yes (and can be filtered on). Of course YouTube doesn't know the short names of iris-hep people, so they are not currently in the yml.

**Comment by davidlange6** [comment]
we lack meta-data to tie presentations to videos (or unique identifiers to tie together). Indico could be mined for that, as presentations have indico links and videos have indico meeting links. 

I could look at adding the video yml name to  presentations. That should be possible (and automatable)

**Comment by davidlange6** [comment]
(but not quick to develop)

**Comment by henryiii** [comment]
Up to you when you want to merge. Needs iteration, but can iterate after it goes in (verified the one video does show up locally)

**Comment by davidlange6** [comment]
will merge - a lot of the missing info comes from the team in the end

**Comment by davidlange6** [comment]
while the one example video on https://iris-hep.org/ia.html works, my videos page does not (https://iris-hep.org/videos.html). Will make a followup assuming I understand it

**Pull request merged**
