### PR TITLE
Add hep_tables vCHEP submission

### PR DESCRIPTION
**Pull request by gordonwatts**
Link to the inspire paper

### CODE REVIEW

**Comment by henryiii** [comment]
One commit. So beautiful! :)

**Comment by gordonwatts** [comment]
Did it from the github web interface UI... Going to blow away my local copy before I do the next update... ;-)

**Comment by matthewfeickert** [comment]
@gordonwatts I think @henryiii, @kratsg, and I would also advocate for using [the GitHub CLI](https://cli.github.com/). :)  Very elegant, well thought out API, and useful!

**Comment by henryiii** [comment]
Great, colorful output, too. If it was written in Python, I'd swear it used `rich`. :)

**Comment by henryiii** [comment]
Doesn't save you from making branches though.

**Comment by gordonwatts** [comment]
> @gordonwatts I think @henryiii, @kratsg, and I would also advocate for using [the GitHub CLI](https://cli.github.com/). :) Very elegant, well thought out API, and useful!

I will look into it. But the nice thing about the web is, no install needed!

**Comment by henryiii** [comment]
For a single file, I do very often use the web UI. ;)

**Pull request merged**
