### PR TITLE
Add information for Suchandra Thapa

### PR DESCRIPTION
**Pull request by sthapa**

### CODE REVIEW

**Comment by bbockelm** [comment]
@sthapa - can you resize the image downward a bit?  ~1MB is a bit large.  I don't know the exact resolution to use but maybe @henryiii has a suggestion?

**Comment by sthapa** [comment]
Will do

**Comment by bbockelm** [comment]
@sthapa - any updates on this?  We wanted to start merging things in in a few hours.

**Comment by sthapa** [comment]
Updated the image size to the 320x 427 .  It's now ~64KB

**Review by bbockelm — APPROVED** [review]
LGTM

**Pull request merged**
