### PR TITLE
feat: add badge for project maturity to project pages

### PR DESCRIPTION
**Pull request by henryiii**
Screen Shot 2022-05-06 at 3 17 38 PM

### CODE REVIEW

**Comment by davidlange6** [comment]
Definitely useful - thought to me the location is a bit invasive as we will presumably eventually have N of these. Perhaps its just a matter of left justifying them?

**Comment by henryiii** [comment]
A small group of badges would still be okay. Though what other badges are expected?

**Comment by henryiii** [comment]
I can left justify (and add a little space) if you think that's better. It's not the same style as the project badges (like on PyHF's page).

**Comment by davidlange6** [comment]
A badge around the irishep role within the project is coming I think
(The way it was discussed was really two badges)

On May 6, 2022 9:54 PM, Henry Schreiner ***@***.***> wrote:

A small group of badges would still be okay. Though what other badges are expected?

**Comment by henryiii** [comment]
As long as the badges were not wider than the title (approximately) I think it would work centered - probably about 3.

**Pull request merged**
