### PR TITLE
Adding more projects

### PR DESCRIPTION
**Pull request by henryiii**
This should not be merged until #91 is merged. Adding more projects, mostly from Scikit-HEP.

### CODE REVIEW

**Comment by davidlange6** [comment]
hi @henryiii - this is still in draft (and does not merge) - I assume you will update it?

**Comment by henryiii** [comment]
Yes, I want to go through one more pass and add a few other projects.

**Comment by henryiii** [comment]
I would also like to ask @jpivarski to take a look at the projects I am adding that he is part of...

**Comment by jpivarski** [comment]
The uproot one doesn't have the plots that the second paragraph refers to, but we can just remove that second paragraph. (It was a later addition, anyway.)

**Comment by henryiii** [comment]
I think this can go in as is, and I can add more projects later. Updated with Jim's suggestion.

**Pull request merged**
