### PR TITLE
Add Derek Weitzel's PEARC presentation

### PR DESCRIPTION
**Pull request by djw8605**

### CODE REVIEW

**Comment by henryiii** [comment]
Looks like the list of Focus areas is unsupported. We should be able to support this. TODO.

**Comment by bbockelm** [comment]
> Looks like the list of Focus areas is unsupported 

You sure about that?  I recall adding support for lists in the past...

**Comment by henryiii** [comment]
That's what the error seems to say; it's comparing a list with a list in Liquid somehow. The only list I see is the focus-area list. It was supposed to be supported, so debugging is needed. I can look at it later today.

**Comment by henryiii** [comment]
> You sure about that? I recall adding support for lists in the past...

The error was confusing; it was actually that the liquid was very picky about the date format. I'll either fix that or add a check for it that gives a nicer error!

**Comment by henryiii** [comment]
There's a nice, clear message now and it fails in the checking stage if the date does not pass, rather than in a weird Liquid error.

**Pull request merged**
