### PR TITLE
Add Jerry Ling's fellowship info (which is a bit late).

### PR DESCRIPTION
**Pull request by jpivarski**
This is coming a bit late because the grad fellowships were separate from the undergrad ones.

I followed the example of #1477 to try to format this properly.

@Moelf, if you want to make any changes (such as choice of picture, etc.), please do. I gave you access to my fork of the iris-hep.org repository; you can make edits directly on this branch until it is merged. In fact, I should ask you for an explicit review so that it doesn't get merged until you approve it.

### CODE REVIEW

**Comment by Moelf** [comment]
Done

**Comment by jpivarski** [comment]
New photo fits with the style and aspect ratio of the others on https://iris-hep.org/fellows.html better.

Okay, this PR is ready to merge!

**Comment by Moelf** [comment]
actually let me match the aspect ratio exactly

**Comment by Moelf** [comment]
done (unsurprisingly confused by GIMP)

**Pull request merged**
