### PR TITLE
Citation through Inspire ID

### PR DESCRIPTION
**Pull request by jpivarski**
@pelmer, this is the update.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@jpivarski, @henryiii can correct me if I'm wrong, but I think for this to build out correctly with INSPIRE you need to strip everything but the [fields described here](https://iris-hep.org/docs/add_publication).

This was my experience when building the site locally for PR #595.

**Comment by henryiii** [comment]
No,  if you have an `inspire-id` file, it will look up the fields, and then set them only if not already set. So you can override any field you need to.

**Comment by jpivarski** [comment]
I don't know where this shows up, in order to test it, but are the fields currently fine? If they are, I'll merge this PR (or anyone who knows that this is correct can merge it).

**Comment by henryiii** [comment]
I can try this locally in 45 mins or so (👶🍼)

**Comment by jpivarski** [comment]
Those are good Unicode points to have memorized!

I don't need an explicit test if you know offhand that this is the right YAML structure. I know that the Inspire ID is correct (taken from the last part of the URL).

**Comment by matthewfeickert** [comment]
@jpivarski I just built this locally

```
bundle exec rake clobber
bundle exec rake serve
```

and your citation now looks like

AwkwardForth_cite

which if I just copy the text and hyperlink is

> [AwkwardForth: accelerating Uproot with an internal DSL](https://arxiv.org/pdf/2102.13516), J. Pivarski, I. Osborne, P. Das, D. Lange and P. Elmer, arXiv 2102.13516 (24 Feb 2021).

Note though that the URL is still to arXiv and not INSPIRE (as you've left that field in) https://arxiv.org/pdf/2102.13516

**Comment by jpivarski** [comment]
@matthewfeickert Then perhaps this fixes it?

(Thanks for checking!)

**Comment by henryiii** [comment]
Looks fine now to me! :)

**Comment by jpivarski** [comment]
Great, I'll merge it!

Thanks, @henryiii and @matthewfeickert!

**Pull request merged**
