### PR TITLE
Add Garhan Attebury

### PR DESCRIPTION
**Pull request by gattebury**
Adding at request of @kenbloom

### CODE REVIEW

**Comment by davidlange6** [comment]
I chatted with @oshadura - lets discuss consistently handling collaborators before merging. [eg, this is changing current practice]

**Comment by matthewfeickert** [comment]
@davidlange6 @oshadura Just checking in as this has been in draft for ~3 months now. Is Garhan still going to be added in the future, or should this PR get closed?

**Comment by matthewfeickert** [comment]
Closing as this PR is over a year old with no activity.

**Comment by oshadura** [comment]
@matthewfeickert this PR @davidlange6 proposed to discuss over EB meeting some time ago. David, could we discuss it next time?

**Comment by davidlange6** [comment]
We can - but we've not seen much interest in trying to capture all collaborators on projects on our team page since this PR opened, so perhaps there is little to discuss?

**Comment by oshadura** [comment]
I see in this list of ["Full members"](https://iris-hep.org/about/team) we have "Collaborator from US.CMS Ops program", is it not the same?

**Pull request closed without merging**
