### PR TITLE
Adding projects to Shawn's presentations.

### PR DESCRIPTION
**Pull request by ShawnMcKee**

### CODE REVIEW

**Comment by henryiii** [comment]
There is no project called "osg-networking". Is it planned to be added, perhaps?

**Comment by osg-cat** [comment]
@henryiii , I just added a PR (#778) for the Network Monitoring project. Could you take a look at that one and merge if you’re happy? Then this one should be in better shape.

**Comment by osg-cat** [comment]
Hm, will there be a way to re-run the “CI / website (pull_request)” check after #778 is merged?

**Comment by henryiii** [comment]
Yes, just close and reopen, and CI reruns. Look good now!

**Pull request merged**
