### PR TITLE
add team pictures to the focus area pages

### LINKED ISSUE #715: feature request: add team members to focus area pages
Would be nice if a focus area page like this:
https://iris-hep.org/as.html

automatically listed the team members working in the area.
  - either just names or also photos

### PR DESCRIPTION
**Pull request by davidlange6**
closes #715

### CODE REVIEW

**Comment by henryiii** [comment]
Can't we use standard_person_card?

**Comment by davidlange6** [comment]
that's what I started from (perhaps hard to tell that now). I don't think we would want so much space taken up by pictures on the focus area / team pages, so I made them much smaller.

**Comment by henryiii** [comment]
I've started refactoring the looping code a bit. We should be able to use `find` (new in 4.x) and `where` to clean up our loops (https://jekyllrb.com/docs/liquid/filters/), and it's really easy to add a Ruby filter for the more advanced stuff. That should be much more readable / maintainable, and is much faster (liquid is slow due to all the double looping we tend to do).

**Comment by henryiii** [comment]
This doesn't work for focus-areas that don't have projects, like ssc and ssl.

**Pull request merged**
