### PR TITLE
Add Haoran Sun profile

### PR DESCRIPTION
**Pull request by hswhhe-uiuc**

### CODE REVIEW

**Comment by pelmer** [comment]
Hi Haoran, please provide a picture file which is <150kB, per the instructions.

**Comment by rct225** [comment]
Hi @hswhhe-uiuc you need to reduce the size of your profile image and your markdown file is formatted incorrectly - see https://raw.githubusercontent.com/iris-hep/iris-hep.github.io/master/_codas-hep-students/2023/example-template.md,  Please make these changes.

**Comment by hswhhe-uiuc** [comment]
Hi @pelmer and @rct225 , I have updated my profile with smaller size. Thank you!

**Comment by rct225** [comment]
Your markdown file is still incorrect.  Please see https://raw.githubusercontent.com/iris-hep/iris-hep.github.io/master/_codas-hep-students/2023/example-template.md for an example of what the file should look like.

These should not be in the front matter: 

```
My research:
 Search of displaced lepton pairs using Run 3 data
 A problem I'm grappling with:
 Statistical Uncertainties of ABCD method
 I want to know more about:
 Parallel programming!
```

**Comment by hswhhe-uiuc** [comment]
Sorry about that. I have updated it and it should work now!

**Pull request merged**
