### PR TITLE
Add last three talks (actually a poster and two tutorials).

### PR DESCRIPTION
**Pull request by jpivarski**

### CODE REVIEW

**Comment by jpivarski** [comment]
Hi, @henryiii, I think this CI failure is something deeper than the three items of YAML I'm adding in this PR. To be sure that it wasn't my fault, I merged my fork with the upstream repo and did a fresh PR starting from that state (the old one was #373). I also checked the validity of my YAML file; it loads in PyYAML. This is probably an indicator that master is broken.

**Comment by henryiii** [comment]
```
home/runner/work/iris-hep.github.io-source/iris-hep.github.io-source/_plugins/checks.rb:27:in `key': presentation #23 in _data/people/jpivarski.yml must contain meeting (StandardError)
180
presentation #0 in _data/people/jpivarski.yml must contain location.
```

**Comment by henryiii** [comment]
I think it wants meeting. Location should be there, but no meeting name breaks it.

**Comment by jpivarski** [comment]
Sorry, I didn't notice that line when I looked at the CI output.

None of my presentations have a "location" field; I'm going to have to go back and retroactively add it to all. It's a requirement that I didn't know about (and was only recently enforced?).

**Comment by jpivarski** [comment]
Thanks, that did it!

**Pull request merged**
