### PR TITLE
Create Tetiana-Yushkevych.yml

### PR DESCRIPTION
**Pull request by Tetiana-Yushkevych**

### CODE REVIEW

**Comment by rct225** [comment]
@Tetiana-Yushkevych You don't need to create this file.  You can add the presentation to your fellows page - pages/fellows/Tetiana-Yushkevych.md

**Comment by matthewfeickert** [comment]
@Tetiana-Yushkevych Instead of creating a new PR can you just make those changes here and rename this one to be more appropriate for the addition of your talk?

**Comment by Tetiana-Yushkevych** [comment]
> @Tetiana-Yushkevych You don't need to create this file. You can add the presentation to your fellows page - pages/fellows/Tetiana-Yushkevych.md

I understand. I'm trying to add a presentation to the pages/fellows/Tetiana-Yushkevych.md file

**Comment by matthewfeickert** [comment]
> You can add the presentation to your fellows page - pages/fellows/Tetiana-Yushkevych.md

@Tetiana-Yushkevych Is this something you could do this week?

**Comment by rct225** [comment]
Adding as part of another pull request @rct225

**Pull request closed without merging**
