### PR TITLE
Rct225 refactor

### PR DESCRIPTION
**Pull request by rct225**

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@rct225 This broke basically all of the former IRIS-HEP fellow links. e.g. https://iris-hep.org/fellows/ptemplem.html's project is now improperly linked.

**Comment by rct225** [comment]
Yes.  I see it.  Script was a bit overzealous with changing paths.  fixing it now

**Comment by davidlange6** [comment]
hum, this commit also destroys all history of the fellow project files. Can this not be redone with git mv 

and second, likely this breaks links on other web pages - what is the new convention for pages?

**Comment by rct225** [comment]
Starting last year we adopted a format of using directories with years to segregate the pages and assets by year.

The links appear to be fine since the permalink hasn't changed.  I looked at the main page, the fellows page and the IA page where fellows appear.

I had not thought of the history.  Should we just revert to the point before I started this and then use git mv?

**Comment by davidlange6** [comment]
I would prefer this..


  *   I had not thought of the history. Should we just revert to the point before I started this and then use git mv?

**Comment by rct225** [comment]
OK.  I'll reach out to Henry.

**Comment by rct225** [comment]
I reverted it, but the history was there ... See https://github.com/iris-hep/iris-hep.github.io/commits/rct225-refactor/pages/fellows/2021/4eshanb.md and click "Browse History".  Was there something else you were referring to @davidlange6?  

Henry also tells me that there's no difference between "git mv" and "mv" + "git add" (what I basically did).

Can also see the history with "git log --follow file.txt".

**Pull request merged**
