### PR TITLE
Offboard Mike Stanfield

### PR DESCRIPTION
**Pull request by jcdrake**
Removing Mike Stanfield people page, photo and team membership in Indiana.yml

### CODE REVIEW

**Comment by jcdrake** [comment]
Fixed error with osg-security.md project page.

**Comment by pelmer** [comment]
Normally we don't remove the person's file altogether, but instead change it to "active: false" as for Susan: https://github.com/iris-hep/iris-hep.github.io-source/blob/master/_data/people/HedgeMage.yml

**Comment by jcdrake** [comment]
> Normally we don't remove the person's file altogether, but instead change it to "active: false" as for Susan: https://github.com/iris-hep/iris-hep.github.io-source/blob/master/_data/people/HedgeMage.yml

Is there documentation for offboarding I can point to for OSG internal procedures?

**Comment by jcdrake** [comment]
Closing, resubmitting with "active: false"

**Pull request closed without merging**
