### PR TITLE
Add coffea-casa project

### LINKED ISSUE #672: Create new Coffea-Casa Project Page
Please create a new Coffea Casa project page inside the DOMA area.

Try to have the following
- [ ] Project description is up-to-date and reflects the current status of the project.
- [ ] One or two figures explaining the architecture of the project and scale / performance results (such as screenshots from monitoring or a figure reproduced from a figure), as applicable.
- [ ] Recent accomplishments (particularly if they are checking off an NSF milestone) and plans / research directions for the next year or so.
- [ ] Team section has all the right people listed.
- [ ] All relevant papers are listed under publications.  Papers should acknowledge IRIS-HEP.
- [ ] All relevant presentations are uploaded.  Presentations should acknowledge IRIS-HEP.

### PR DESCRIPTION
**Pull request by oshadura**
FYI coffea-casa logo is still under development, I added a placeholder and will update as soon as we will have a draft.

cc:  @kenbloom @bbockelm 

Fixes: https://github.com/iris-hep/iris-hep.github.io-source/issues/672

### CODE REVIEW

**Comment by bbockelm** [comment]
@oshadura - wonderful start!  Looking at the checklist I put together, here are some things that might be missing:

- *Recent accomplishments (particularly if they are checking off an NSF milestone) and plans / research directions for the next year or so*.
- *All relevant papers are listed under publications*:  Is the preprint of the vCHEP paper posted?
- *All relevant presentations are uploaded*: Certainly we have some presentations to link, no?  Can you comb through your presentations from the last 6 months and add them here?

**Comment by oshadura** [comment]
@bbockelm as I understood papers and presentations will be appended automatically to the page based on our profiles mentioned on it? (I think linked from here: https://iris-hep.org/presentations/byperson.html and https://iris-hep.org/publications/all.html)

I was checking as an example https://iris-hep.org/projects/caching.html (sources https://github.com/iris-hep/iris-hep.github.io-source/blob/master/pages/projects/caching.md) and presentation/publications were 'magically' added without adding explicitly to .md file?

If it is true, then all recent presentation and vchep paper will be appended...

**Comment by oshadura** [comment]
> @oshadura - wonderful start! Looking at the checklist I put together, here are some things that might be missing:
> 
>      _Recent accomplishments (particularly if they are checking off an NSF milestone) and plans / research directions for the next year or so_.

Updated.

> 
>      _All relevant papers are listed under publications_:  Is the preprint of the vCHEP paper posted?

I added them some time ago, they should be appended automatically

> 
>      _All relevant presentations are uploaded_: Certainly we have some presentations to link, no?  Can you comb through your presentations from the last 6 months and add them here?

I added them some time ago, they should be appended automatically

**Comment by oshadura** [comment]
@bbockelm please check! I think everything is ready, except missing logo...

**Comment by bbockelm** [comment]
@oshadura - I think this is good enough for a first draft.  I'm going to merge now and if we see problems I will open a new issue for you.

**Pull request merged**
