### PR TITLE
added news item for story about Bei Wang

### PR DESCRIPTION
**Pull request by rct225**

### CODE REVIEW

**Comment by rct225** [comment]
@henryiii Any thoughts as to why this is failing?  Not sure if you're the right one to ask.

**Comment by henryiii** [comment]
Looks like a problem with the Ubuntu repository. Should fix it self in a little while, I think.

**Comment by rct225** [comment]
Thanks @henryiii .  Just wanted to make sure I didn’t break something.

**Comment by rct225** [comment]
@henryiii This still seems to be failing.

**Comment by henryiii** [comment]
Fixed by @matthewfeickert  in #316.

**Comment by rct225** [comment]
Thank you @henryiii and @matthewfeickert.

**Pull request merged**
