### PR TITLE
Adding info for CODAS HEP 2024

### PR DESCRIPTION
**Pull request by Payal7890**
_codas-hep-students/2024/Payal7890.md

assets/images/codas-hep/2024/Payal-Roy.jpg

### CODE REVIEW

**Comment by pelmer** [comment]
Hi Payal, did you mv rather than copy the example template file?

**Comment by Payal7890** [comment]
Hello,

  I edited the file. Was that the wrong way?

**Comment by pelmer** [comment]
Hi, it looks like you "Update(d) and rename(d) example-template.md to Payal7890.md"

**Comment by Payal7890** [comment]
Hello, I just uploaded the Payal7890.md to the CoDAS HEP 2024 repository.

**Comment by Payal7890** [comment]
Should I raise a new pull request?

**Comment by Payal7890** [comment]
Hello,
  I just realised that I forgot to edit "example-name" in my markdown file.
I have added a new file "Payal7890.md" where everything is updated. I am
sorry for the inconvenience.

Best
Payal

**Comment by rct225** [comment]
You'll have to make another PR

**Pull request merged**
