### PR TITLE
Add new fellows project

### PR DESCRIPTION
**Pull request by gordonwatts**

### CODE REVIEW

**Comment by henryiii** [comment]
27 commits for 6 lines of code? Almost don't want to ask, but you could use a [block scalar](https://yaml-multiline.info) to simplify that long string. Also would be nice to remove the blank line. Minor cosmetic things though. :)

**Comment by gordonwatts** [comment]
I have no idea what a block scalar is.

The problem would be fixed if I would delete this repo and then create a new one. I think it is because I've been making the mods on master, and not a branch in my clone. In the end, only one file is ever changed, and all the other commits are already part of the iris-hep repo.

**Comment by henryiii** [comment]
That's why I make block-scalar a link. Basically this:

```yaml
key: >
  Some very
  long text on
  many lines.
```

Is exactly the same as this:

```yaml
key: "Some very long text on many lines."
```

I've manually converted all of them to block scalars now, so that's fine. Feel free to check the current version.

Generally I delete master on my fork, so that "master" locally points to upstream/master rather than henryiii/master (which does't exist, because it's deleted on my fork). Then you can make branches for commits. If you want to use master, you can do a `git reset upstream/master` to reset it to the remote.

Though you are still one of the very rare examples of having dozens of commits but only a tiny change, even when I see other contributors using master, so you still must have some special talent for that somehow. :)

**Comment by gordonwatts** [comment]
Ah - ok - I do know what a block-scalar is! Just didn't know it was called that. I saw that change - thank you!

As far as deleting master, that is a great idea! I'd never thought of that.

**Pull request merged**
