### PR TITLE
docs: add fellows projects for Histograms

### PR DESCRIPTION
**Pull request by henryiii**

### CODE REVIEW

**Comment by henryiii** [comment]
@rct225 is this okay to merge? It's a little late, sorry!

**Comment by henryiii** [comment]
Also, @jpivarski, @hdembinski, would you like to be listed as a mentor or extra contact for either of these?

**Comment by HDembinski** [comment]
Sure, btw these are great projects.

**Comment by henryiii** [comment]
Let's merge to make sure they don't get missed, based on an email that just got sent out. Happy to modify later.

**Pull request merged**
