### PR TITLE
Update ACTS project page

### PR DESCRIPTION
**Pull request by gagnonlg**
This PR:

- Updates the ACTS project member's list
- Adds a paragraph to the project description

### CODE REVIEW

**Comment by gagnonlg** [comment]
Marked as WIP because we also need to update the presentations.

**Comment by henryiii** [comment]
Please use draft mode for things that should not be merged yet.

**Comment by gagnonlg** [comment]
@henryiii This is basically ready but I have one question before undrafting this. We have a collaborator (Tomohiro) in the team list who used to be a fellow but was never a full iris-hep member so he is not in the people directory. We would still like his presentations to show up in the ACTS list; is there a way to do that? Thanks!

**Comment by henryiii** [comment]
Do they get picked up from fellows? If not, likely a bug.

**Comment by davidlange6** [comment]
Fellows are poorly (or not at all) connected to projects currently.

On Apr 30, 2021 6:35 AM, Henry Schreiner ***@***.***> wrote:

Do they get picked up from fellows? If not, likely a bug.

**Comment by henryiii** [comment]
That's fixable, let's add fellows presentations as if they would show up, and we can add them (slowly) to the various places presentations are listed.

**Comment by gagnonlg** [comment]
Thanks for the clarification @henryiii & @davidlange6 . I now made sure that the fellows & former iris-hep members are in our team list with the right shortname. Should be good to go now!

**Pull request merged**
