### PR TITLE
Offboard Mike Stanfield, reactivate Susan Sons

### PR DESCRIPTION
**Pull request by jcdrake**
Make changes to people yml files for mtstanfield and HedgeMage to deactivate Mike Stanfield and re-add Susan Sons to OSG security.  

Edited osg-security.md on project page to reflect changes

Removed mtstanfield from Indiana.yml

### CODE REVIEW

**Comment by pelmer** [comment]
I guess I'm confused: is Susan now active again? She wasn't in the Year 4 draft budget I got for IU.

**Comment by jcdrake** [comment]
I sent you an email regarding Susan's status.  Edited Indiana.yml to fix build issue.

**Comment by henryiii** [comment]
Good to go now?

**Comment by jcdrake** [comment]
Yes.

Sent from Nine<http://www.9folders.com/>
________________________________
From: Henry Schreiner ***@***.***>
Sent: Friday, July 23, 2021 4:00 PM
To: iris-hep/iris-hep.github.io-source
Cc: Drake, Josh; Author
Subject: [External] Re: [iris-hep/iris-hep.github.io-source] Offboard Mike Stanfield, reactivate Susan Sons (#1041)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Good to go now?

**Pull request merged**
